"""empty message

Revision ID: 1db30c2ec33e
Revises: 42285bcf7e98
Create Date: 2025-02-27 19:27:32.945043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db30c2ec33e'
down_revision = '42285bcf7e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.Integer(), nullable=True, comment='1:PO,2:Quotation,3:ISO,4:Warranty'),
    sa.Column('productForSalesModel_id', sa.Integer(), nullable=True),
    sa.Column('flag_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['productForSalesModel_id'], ['productForSalesModel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productForSalesModel_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['productForSalesModel_id'], ['productForSalesModel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('md_image')
    op.drop_table('files')
    # ### end Alembic commands ###
