"""empty message

Revision ID: 42285bcf7e98
Revises: 6b4b573ddc25
Create Date: 2025-02-27 19:03:32.258556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42285bcf7e98'
down_revision = '6b4b573ddc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productForSalesModel', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'productForSalesModel', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productForSalesModel', type_='foreignkey')
    op.drop_column('productForSalesModel', 'country_id')
    # ### end Alembic commands ###
