"""empty message

Revision ID: 44b80665a474
Revises: 1db30c2ec33e
Create Date: 2025-02-27 19:37:18.015573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44b80665a474'
down_revision = '1db30c2ec33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_for_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('term_of_payment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_of_payment_id'], ['term_of_payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('productForSalesModel')
    op.add_column('files', sa.Column('product_for_sales_id', sa.Integer(), nullable=True))
    op.drop_constraint('files_productForSalesModel_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'product_for_sales', ['product_for_sales_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'productForSalesModel_id')
    op.add_column('md_image', sa.Column('product_for_sales_id', sa.Integer(), nullable=True))
    op.drop_constraint('md_image_productForSalesModel_id_fkey', 'md_image', type_='foreignkey')
    op.create_foreign_key(None, 'md_image', 'product_for_sales', ['product_for_sales_id'], ['id'], ondelete='CASCADE')
    op.drop_column('md_image', 'productForSalesModel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('md_image', sa.Column('productForSalesModel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'md_image', type_='foreignkey')
    op.create_foreign_key('md_image_productForSalesModel_id_fkey', 'md_image', 'productForSalesModel', ['productForSalesModel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('md_image', 'product_for_sales_id')
    op.add_column('files', sa.Column('productForSalesModel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_productForSalesModel_id_fkey', 'files', 'productForSalesModel', ['productForSalesModel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'product_for_sales_id')
    op.create_table('productForSalesModel',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"productForSalesModel_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('term_of_payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='productForSalesModel_country_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], name='productForSalesModel_period_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], name='productForSalesModel_product_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_of_payment_id'], ['term_of_payment.id'], name='productForSalesModel_term_of_payment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='productForSalesModel_pkey')
    )
    op.drop_table('product_for_sales')
    # ### end Alembic commands ###
