"""empty message

Revision ID: 6b4b573ddc25
Revises: bbd61f481209
Create Date: 2025-02-27 18:55:54.520008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4b573ddc25'
down_revision = 'bbd61f481209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productForSalesModel', 'product_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('productForSalesModel', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('productForSalesModel', 'term_of_payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('productForSalesModel_country_id_fkey', 'productForSalesModel', type_='foreignkey')
    op.drop_column('productForSalesModel', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productForSalesModel', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('productForSalesModel_country_id_fkey', 'productForSalesModel', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    op.alter_column('productForSalesModel', 'term_of_payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('productForSalesModel', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('productForSalesModel', 'product_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
