"""empty message

Revision ID: 90a7e3ea7fa0
Revises: 3b54437f09ad
Create Date: 2025-03-02 14:32:00.657859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a7e3ea7fa0'
down_revision = '3b54437f09ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_for_sales', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_for_sales', 'price')
    # ### end Alembic commands ###
