"""empty message

Revision ID: 93bea4917785
Revises: 93eb8f1394ff
Create Date: 2025-04-24 00:34:33.081512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93bea4917785'
down_revision = '93eb8f1394ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_for_sales', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('product_for_sales', 'product_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_for_sales', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_for_sales', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_for_sales', 'term_of_payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_for_sales', 'term_of_payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_for_sales', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_for_sales', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_for_sales', 'product_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_for_sales', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
