"""empty message

Revision ID: 93eb8f1394ff
Revises: 90a7e3ea7fa0
Create Date: 2025-03-21 10:00:44.535424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eb8f1394ff'
down_revision = '90a7e3ea7fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('md_image', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('md_image', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_for_sales', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('product_for_sales', sa.Column('end_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_for_sales', 'end_at')
    op.drop_column('product_for_sales', 'start_at')
    op.drop_column('md_image', 'updated_at')
    op.drop_column('md_image', 'created_at')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    # ### end Alembic commands ###
