"""empty message

Revision ID: bd94a18d9a6c
Revises: d33ace792ffc
Create Date: 2025-02-27 19:40:20.992148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd94a18d9a6c'
down_revision = 'd33ace792ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_for_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('term_of_payment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_of_payment_id'], ['term_of_payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.Integer(), nullable=True, comment='1:PO,2:Quotation,3:ISO,4:Warranty'),
    sa.Column('product_for_sales_id', sa.Integer(), nullable=True),
    sa.Column('flag_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_for_sales_id'], ['product_for_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('product_for_sales_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_for_sales_id'], ['product_for_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('productForSalesModel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productForSalesModel',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"productForSalesModel_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('term_of_payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='productForSalesModel_country_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], name='productForSalesModel_period_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], name='productForSalesModel_product_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_of_payment_id'], ['term_of_payment.id'], name='productForSalesModel_term_of_payment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='productForSalesModel_pkey')
    )
    op.drop_table('md_image')
    op.drop_table('files')
    op.drop_table('product_for_sales')
    # ### end Alembic commands ###
